const bios = [
    "Join us now: {{link}} - Crypto trading powered by AI.",
        "Next-gen trading strategies with AI insights. Get in early: {{link}}",
        "Looking for the next big move? AI tracks it all! Join: {{link}}",
        "{{link}} - Smart money uses AI. Be part of it now!",
        "Revolutionizing crypto with AI-driven insights. Join today: {{link}}",
        "Pump smarter with AI-backed predictions. Get started: {{link}}",
        "Trade like a pro with AI-powered signals. Join now: {{link}}",
        "Find hidden gems before they moon. AI-powered trading: {{link}}",
        "Automated crypto signals for maximum profits. Join us: {{link}}",
        "Exclusive AI-driven trading community. Don't miss out: {{link}}",
        "AI meets crypto trading. Be part of the future: {{link}}",
        "Unlock the power of AI in crypto. Join our movement: {{link}}",
        "Data-driven crypto strategies for serious traders. Join: {{link}}",
        "AI-powered trading insights for top-tier results. Join now: {{link}}",
        "Next-level crypto gains with AI precision. Get in here: {{link}}",
        "{{link}} - Your competitive edge in crypto trading - AI-powered!",
        "AI does the work, you take the profit. Join us: {{link}}",
        "Be early to the AI-driven revolution in crypto trading. Join: {{link}}",
        "AI-backed trading strategies that deliver. Get started: {{link}}",
        "Join the smartest crypto traders using AI for insights. Start now: {{link}}",
        "{{link}} - Stay ahead of the curve with AI-driven crypto strategies!",
        "AI reveals the best trades before anyone else. Join now: {{link}}",
        "Crypto's future is AI-driven. Be an early adopter! {{link}}",
        "Make the smartest moves in crypto with AI-driven insights. Join: {{link}}",
        "Automated AI trading signals giving top-tier results. Join: {{link}}",
        "{{link}} - The AI advantage in crypto trading is here!",
        "Find the best pumps before they explode. AI-powered: {{link}}",
        "Let AI find the next big pump for you! Join now: {{link}}",
        "Stay ahead with AI-powered market analysis. Join: {{link}}",
        "Crypto moves fast, but AI moves faster! Be part of it: {{link}}",
        "{{link}} - Maximize your crypto profits with AI trading!",
        "Smart traders use AI. Join our exclusive community: {{link}}",
        "Find hidden gems before the masses with AI signals. Join now: {{link}}",
        "Trade intelligently with AI-driven market predictions! {{link}}",
        "Your AI trading advantage starts here. Get in now: {{link}}",
        "{{link}} - AI-based trading strategies delivering real results!",
        "Predict crypto trends before they go viral with AI! Join now: {{link}}",
        "AI insights for massive crypto gains. Don't miss out: {{link}}",
        "Join the AI-powered crypto revolution today! {{link}}",
        "AI-driven trading strategies with high accuracy. Join: {{link}}",
        "The next crypto wave is AI-powered. Ride it with us! {{link}}",
        "{{link}} - Make better trades with AI-driven crypto insights!",
        "Join our AI-driven crypto community and trade smarter! {{link}}",
        "Let AI take your crypto trading to the next level! Join now: {{link}}",
        "Unlock hidden market opportunities with AI insights! {{link}}",
        "{{link}} - Your personal AI crypto assistant is waiting!",
        "AI-backed crypto signals for massive gains. Join: {{link}}",
        "Data-driven AI strategies for top-tier traders. Get in now: {{link}}",
        "Crypto's best-kept secret? AI-powered trading insights! {{link}}",
        "Stay ahead with real-time AI market insights. Join now: {{link}}",
        "{{link}} - Trade smarter, not harder, with AI-driven strategies!",
        "Crypto AI signals that actually work! Join the group now: {{link}}",
        "Automate your success with AI-driven market strategies! {{link}}",
        "Join the only crypto community using AI for trading! {{link}}",
        "{{link}} - The smartest AI-powered traders are here. Be one of them!",
        "AI reveals market trends before anyone else. Join: {{link}}",
        "Trading made simple with AI-powered market insights. Join: {{link}}",
        "AI-driven insights for serious crypto traders. Get in now: {{link}}",
        "{{link}} - Be ahead of the market with AI-driven signals!",
        "Crypto made smarter with AI-backed predictions. Join now: {{link}}",
        "Find the best trades before the crowd moves. AI-powered: {{link}}",
        "Trade better, earn more! AI-powered trading signals: {{link}}",
        "Maximize your profits with AI trading algorithms. Join now: {{link}}",
        "{{link}} - AI-powered trading community with real results!",
        "Your edge in crypto trading? AI-driven insights! Join now: {{link}}",
        "AI-driven trading community for top-tier strategies. Join: {{link}}",
        "Get real-time AI-powered market insights today! {{link}}",
        "{{link}} - The AI trading revolution is happening now. Be part of it!",
        "Crypto's future is AI-powered. Get ahead now: {{link}}",
        "Find hidden market gems before they go viral. AI-backed: {{link}}",
        "Trade smarter, not harder, with AI-powered insights! Join now: {{link}}",
        "{{link}} - Our AI finds the best trades before anyone else!",
        "Be the first to act with AI-powered trading insights! Join: {{link}}",
        "The next big crypto moves start with AI! Join us: {{link}}",
        "{{link}} - Early signals, big profits. AI-driven crypto strategies!",
        "Unlock crypto market secrets with AI-powered signals. Join now: {{link}}"
];

export function getRandomBio() {
    return bios[Math.floor(Math.random() * bios.length)];
}
