const comments = [
    "Don't miss out! Join our AI-powered crypto revolution now! {{link}}",
        "Pumping crypto with AI? We got you! Join our Telegram: {{link}}",
        "New AI-driven token strategy! Be part of the next 100x gem: {{link}}",
        "Looking for the next big pump? Our AI tracks it all! Join now: {{link}}",
        "AI meets crypto, the future is here! Join us: {{link}}",
        "Next-gen crypto with AI insights! Stay ahead of the market: {{link}}",
        "Predict the next pump with AI! Exclusive community: {{link}}",
        "Smart money moves with AI! Join the top traders now: {{link}}",
        "Revolutionary AI-driven trading strategies! Join our group: {{link}}",
        "Join our AI crypto network, first movers win! {{link}}",
        "Automated trading insights from AI! Get in early: {{link}}",
        "Follow the data, follow the pumps! AI-powered insights: {{link}}",
        "Discover AI-powered crypto signals! Don't miss out: {{link}}",
        "Your AI advantage in crypto starts now! Join here: {{link}}",
        "AI-driven trading for the smart investor! Join us: {{link}}",
        "Unlock the future of crypto with AI-driven insights! {{link}}",
        "Don't trade blind! Use AI-powered analysis. Join us: {{link}}",
        "Top traders are using AI, are you? Join here: {{link}}",
        "Pump smarter, not harder! AI-driven crypto community: {{link}}",
        "Find the next big move before the masses! AI-powered: {{link}}",
        "Crypto's future is AI, join our leading group today: {{link}}",
        "Profitable trades start with AI, get in now! {{link}}",
        "Let AI do the heavy lifting in your crypto journey! {{link}}",
        "Next-level crypto gains with AI insights! Join us: {{link}}",
        "AI-powered signals catching early pumps! Don't miss it: {{link}}",
        "Turn market data into profits using AI! Join our group: {{link}}",
        "Get ahead of the whales with AI insights! Join here: {{link}}",
        "Exclusive AI trading tips in our community! Join now: {{link}}",
        "Join the AI-powered crypto revolution! Stay ahead: {{link}}",
        "Crypto moves fast, our AI moves faster! Be first: {{link}}",
        "Make better trades with AI predictions! Join today: {{link}}",
        "Harness AI for smarter trading decisions! Join us: {{link}}",
        "AI-powered trading is the edge you need! Get in now: {{link}}",
        "Stay ahead in crypto using AI-driven strategies! {{link}}",
        "Join the next AI-powered crypto movement! Be early: {{link}}",
        "AI reveals the best trades, see it for yourself! {{link}}",
        "Join the only AI-driven pump tracking community! {{link}}",
        "The power of AI in your hands, join our group today! {{link}}",
        "AI-driven pumps? Get in before the hype starts! {{link}}",
        "Trade smarter, not harder! AI-powered insights: {{link}}",
        "Follow the AI, follow the money, join us here: {{link}}",
        "Let AI maximize your crypto gains! Join now: {{link}}",
        "AI is changing crypto trading, don't be left behind! {{link}}",
        "Data-driven profits with AI analysis! Join here: {{link}}",
        "Predict the next move with AI-backed insights! {{link}}",
        "Crypto trends before they happen, AI predicts it! {{link}}",
        "The AI-driven crypto edge you've been waiting for! {{link}}",
        "AI is the key to smart crypto trading, unlock it here: {{link}}",
        "Spot hidden gems before they pump! AI-powered: {{link}}",
        "Trade like a pro with AI-assisted crypto insights! {{link}}",
        "Be the first to act with AI-powered signals! Join now: {{link}}",
        "Automate your success with AI-driven market insights! {{link}}",
        "Crypto moves fast, AI moves faster! Stay ahead: {{link}}",
        "Let AI guide your next trade! Exclusive insights: {{link}}",
        "Trading with AI? It's the future! Join us here: {{link}}",
        "AI finds the hidden pumps before anyone else! {{link}}",
        "Next-gen crypto trading starts with AI, get in now: {{link}}",
        "Maximize your crypto potential with AI insights! {{link}}",
        "AI-backed trading strategies for real results! Join now: {{link}}",
        "Make informed moves with AI-powered insights! {{link}}",
        "The next crypto wave is AI-driven! Ride it with us: {{link}}",
        "Join the AI revolution in crypto! Smart trading starts here: {{link}}",
        "Find the pumps before they explode with AI analysis! {{link}}",
        "AI-driven trading strategies at your fingertips! {{link}}",
        "Predict crypto trends before they happen, AI-powered! {{link}}",
        "Exclusive AI-backed trading signals inside! Join here: {{link}}",
        "Early signals, big gains! AI-driven crypto strategies: {{link}}",
        "AI insights for real crypto profits! Get in early: {{link}}",
        "Crypto moves made smarter with AI! Join our group: {{link}}",
        "Let AI take your crypto trading to the next level! {{link}}",
        "The edge you need in crypto trading, AI-powered! {{link}}",
        "AI-based trading strategies that actually work! Join now: {{link}}",
        "Trade intelligently with AI-driven market predictions! {{link}}",
        "Crypto's best-kept secret? AI-powered trading insights! {{link}}",
        "AI reveals market trends before they go viral! Join now: {{link}}",
        "Trading made simple with AI-powered analysis! {{link}}",
        "AI-driven insights for massive crypto gains! Join here: {{link}}",
        "Be ahead of the market with AI-driven strategies! {{link}}",
        "Get real-time AI-powered market insights now! {{link}}",
        "Crypto made smarter with AI-backed predictions! {{link}}",
        "Find the hidden gems before they moon! AI-backed tips: {{link}}",
        "Trade better, earn more! AI-powered trading insights: {{link}}",
        "The only crypto community using AI for trading! {{link}}",
        "AI-powered trading signals with real results! Join now: {{link}}",
        "Your personal AI crypto assistant is here! Join us: {{link}}",
        "Data-driven AI strategies for serious crypto traders! {{link}}",
        "Crypto AI signals that actually work! Join the group: {{link}}",
        "Find the best trades before they go viral! AI-powered: {{link}}",
        "Our AI does the work, you reap the profits! Join now: {{link}}",
        "AI finds the best trades before the crowd! Be early: {{link}}",
        "Real AI, real gains! Join our exclusive community: {{link}}",
        "Crypto's future is AI-driven, join us before the masses! {{link}}",
        "Profitable crypto signals powered by AI! Join now: {{link}}"
];

export function getRandomComment() {
    return comments[Math.floor(Math.random() * comments.length)];
}
